### ISSUE TITLE
无法下载检测到病毒

### ISSUE THREAD

**Issue by initialencounter** [auula/typikon#6]
![90661c9050c377f2d20378929e896721](https://github.com/auula/typikon/assets/109729945/69f29dca-d39f-4237-bb0e-93f5ea1e9d11)

允许威胁后，无法执行
![image](https://github.com/auula/typikon/assets/109729945/d5053f02-cd50-4caa-a6ce-5f9ac895aded)

版本：v0.1.1
平台：windows-amd64
系统：Windows 11 专业工作站版

**Comment by auula** [comment]
谢谢你的反馈，可能存在误报，你可以检查仓库的源代码，确认代码安全性，如果不相信源代码安全程度可以尝试通过源代码编译安装的方式进行编译，步骤：

1.在你的电脑上安装 git 通过 git clone 这个仓库。
2.进入到源代码目录执行 cargo build --relese 命令执行编译安装。

**Comment by auula** [comment]
> 谢谢你的反馈，可能存在误报，你可以检查仓库的源代码，确认代码安全性，如果不相信源代码安全程度可以尝试通过源代码编译安装的方式进行编译，步骤：
> 
> 1.在你的电脑上安装 git 通过 `git clone` 这个仓库。 2.进入到源代码目录执行 `cargo build --relese --verbose` 命令执行编译安装。

**Comment by auula** [comment]
> ![90661c9050c377f2d20378929e896721](https://private-user-images.githubusercontent.com/109729945/346574373-69f29dca-d39f-4237-bb0e-93f5ea1e9d11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1NzIzMDUsIm5iZiI6MTcyMDU3MjAwNSwicGF0aCI6Ii8xMDk3Mjk5NDUvMzQ2NTc0MzczLTY5ZjI5ZGNhLWQzOWYtNDIzNy1iYjBlLTkzZjVlYTFlOWQxMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMFQwMDQwMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZDk0Zjg3YmNiNWM0ODJmMDM2MmUwYWJhM2RlZTBhMjcxNGM4MDQ5ODI4MTJjODQ0NzVjZmFkZGRiOGEyYzNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Cx4I4exj9WEc_tSC0F0B4H4XjzKkUKZgEBXS-JepGmA)
> 
> 允许威胁后，无法执行 ![image](https://private-user-images.githubusercontent.com/109729945/346575260-d5053f02-cd50-4caa-a6ce-5f9ac895aded.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1NzIzMDUsIm5iZiI6MTcyMDU3MjAwNSwicGF0aCI6Ii8xMDk3Mjk5NDUvMzQ2NTc1MjYwLWQ1MDUzZjAyLWNkNTAtNGNhYS1hNmNlLTVmOWFjODk1YWRlZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMFQwMDQwMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZjg0MTMxYTZhNjliNmI2ZjdhZDVmN2M4YjE0Y2I0N2ZiOGUyYWI2YjRiNmZlNzFjYTRlZmQxOTNmYTYzZDQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.v2DafLzxLvdxhITM5GqTMbjUb43jj85UuMOUbHImeWU)
> 
> 版本：v0.1.1 平台：windows-amd64 系统：Windows 11 专业工作站版

可以使用新版本，我怀疑之前使用压缩打包软件也问题，现在已经修复了：[https://github.com/auula/typikon/releases/tag/v0.1.2](https://github.com/auula/typikon/releases/tag/v0.1.2) ，感谢你的问题反馈。
